// Code generated by mockery v2.53.5. DO NOT EDIT.

package router_mock

import (
	context "context"
	domain "harmony/internal/auth/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockAccountGetter is an autogenerated mock type for the AccountGetter type
type MockAccountGetter struct {
	mock.Mock
}

type MockAccountGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountGetter) EXPECT() *MockAccountGetter_Expecter {
	return &MockAccountGetter_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *MockAccountGetter) Get(_a0 context.Context, _a1 domain.AccountID) (domain.Account, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AccountID) (domain.Account, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AccountID) domain.Account); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(domain.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AccountID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountGetter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAccountGetter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 domain.AccountID
func (_e *MockAccountGetter_Expecter) Get(_a0 interface{}, _a1 interface{}) *MockAccountGetter_Get_Call {
	return &MockAccountGetter_Get_Call{Call: _e.mock.On("Get", _a0, _a1)}
}

func (_c *MockAccountGetter_Get_Call) Run(run func(_a0 context.Context, _a1 domain.AccountID)) *MockAccountGetter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.AccountID))
	})
	return _c
}

func (_c *MockAccountGetter_Get_Call) Return(_a0 domain.Account, _a1 error) *MockAccountGetter_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountGetter_Get_Call) RunAndReturn(run func(context.Context, domain.AccountID) (domain.Account, error)) *MockAccountGetter_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountGetter creates a new instance of MockAccountGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountGetter {
	mock := &MockAccountGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
