// Code generated by mockery v2.53.3. DO NOT EDIT.

package auth_mock

import (
	context "context"
	authdomain "harmony/internal/features/auth/authdomain"

	mock "github.com/stretchr/testify/mock"
)

// MockAccountUpdater is an autogenerated mock type for the AccountUpdater type
type MockAccountUpdater struct {
	mock.Mock
}

type MockAccountUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountUpdater) EXPECT() *MockAccountUpdater_Expecter {
	return &MockAccountUpdater_Expecter{mock: &_m.Mock}
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *MockAccountUpdater) Update(_a0 context.Context, _a1 authdomain.Account) (authdomain.Account, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 authdomain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, authdomain.Account) (authdomain.Account, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, authdomain.Account) authdomain.Account); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(authdomain.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, authdomain.Account) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountUpdater_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAccountUpdater_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 authdomain.Account
func (_e *MockAccountUpdater_Expecter) Update(_a0 interface{}, _a1 interface{}) *MockAccountUpdater_Update_Call {
	return &MockAccountUpdater_Update_Call{Call: _e.mock.On("Update", _a0, _a1)}
}

func (_c *MockAccountUpdater_Update_Call) Run(run func(_a0 context.Context, _a1 authdomain.Account)) *MockAccountUpdater_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(authdomain.Account))
	})
	return _c
}

func (_c *MockAccountUpdater_Update_Call) Return(_a0 authdomain.Account, _a1 error) *MockAccountUpdater_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountUpdater_Update_Call) RunAndReturn(run func(context.Context, authdomain.Account) (authdomain.Account, error)) *MockAccountUpdater_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountUpdater creates a new instance of MockAccountUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountUpdater {
	mock := &MockAccountUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
