// Code generated by mockery v2.53.2. DO NOT EDIT.

package auth_mock

import mock "github.com/stretchr/testify/mock"

// MockDomainEvent is an autogenerated mock type for the DomainEvent type
type MockDomainEvent struct {
	mock.Mock
}

type MockDomainEvent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDomainEvent) EXPECT() *MockDomainEvent_Expecter {
	return &MockDomainEvent_Expecter{mock: &_m.Mock}
}

// NewMockDomainEvent creates a new instance of MockDomainEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDomainEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDomainEvent {
	mock := &MockDomainEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
