// Code generated by mockery v2.53.3. DO NOT EDIT.

package auth_mock

import (
	context "context"
	authdomain "harmony/internal/auth/authdomain"

	core "harmony/internal/core"

	mock "github.com/stretchr/testify/mock"
)

// MockAccountInserter is an autogenerated mock type for the AccountInserter type
type MockAccountInserter struct {
	mock.Mock
}

type MockAccountInserter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountInserter) EXPECT() *MockAccountInserter_Expecter {
	return &MockAccountInserter_Expecter{mock: &_m.Mock}
}

// Insert provides a mock function with given fields: _a0, _a1
func (_m *MockAccountInserter) Insert(_a0 context.Context, _a1 core.UseCaseResult[authdomain.PasswordAuthentication]) (authdomain.PasswordAuthentication, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 authdomain.PasswordAuthentication
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, core.UseCaseResult[authdomain.PasswordAuthentication]) (authdomain.PasswordAuthentication, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, core.UseCaseResult[authdomain.PasswordAuthentication]) authdomain.PasswordAuthentication); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(authdomain.PasswordAuthentication)
	}

	if rf, ok := ret.Get(1).(func(context.Context, core.UseCaseResult[authdomain.PasswordAuthentication]) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountInserter_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockAccountInserter_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 core.UseCaseResult[authdomain.PasswordAuthentication]
func (_e *MockAccountInserter_Expecter) Insert(_a0 interface{}, _a1 interface{}) *MockAccountInserter_Insert_Call {
	return &MockAccountInserter_Insert_Call{Call: _e.mock.On("Insert", _a0, _a1)}
}

func (_c *MockAccountInserter_Insert_Call) Run(run func(_a0 context.Context, _a1 core.UseCaseResult[authdomain.PasswordAuthentication])) *MockAccountInserter_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.UseCaseResult[authdomain.PasswordAuthentication]))
	})
	return _c
}

func (_c *MockAccountInserter_Insert_Call) Return(_a0 authdomain.PasswordAuthentication, _a1 error) *MockAccountInserter_Insert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountInserter_Insert_Call) RunAndReturn(run func(context.Context, core.UseCaseResult[authdomain.PasswordAuthentication]) (authdomain.PasswordAuthentication, error)) *MockAccountInserter_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountInserter creates a new instance of MockAccountInserter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountInserter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountInserter {
	mock := &MockAccountInserter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
