// Code generated by mockery v2.53.5. DO NOT EDIT.

package auth_mock

import (
	context "context"
	domain "harmony/internal/auth/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockEmailChallengeRepository is an autogenerated mock type for the EmailChallengeRepository type
type MockEmailChallengeRepository struct {
	mock.Mock
}

type MockEmailChallengeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailChallengeRepository) EXPECT() *MockEmailChallengeRepository_Expecter {
	return &MockEmailChallengeRepository_Expecter{mock: &_m.Mock}
}

// FindByEmail provides a mock function with given fields: _a0, _a1
func (_m *MockEmailChallengeRepository) FindByEmail(_a0 context.Context, _a1 string) (domain.Account, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Account, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Account); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(domain.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmailChallengeRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockEmailChallengeRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockEmailChallengeRepository_Expecter) FindByEmail(_a0 interface{}, _a1 interface{}) *MockEmailChallengeRepository_FindByEmail_Call {
	return &MockEmailChallengeRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", _a0, _a1)}
}

func (_c *MockEmailChallengeRepository_FindByEmail_Call) Run(run func(_a0 context.Context, _a1 string)) *MockEmailChallengeRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEmailChallengeRepository_FindByEmail_Call) Return(_a0 domain.Account, _a1 error) *MockEmailChallengeRepository_FindByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmailChallengeRepository_FindByEmail_Call) RunAndReturn(run func(context.Context, string) (domain.Account, error)) *MockEmailChallengeRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *MockEmailChallengeRepository) Update(_a0 context.Context, _a1 domain.Account) (domain.Account, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Account) (domain.Account, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Account) domain.Account); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(domain.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Account) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmailChallengeRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockEmailChallengeRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 domain.Account
func (_e *MockEmailChallengeRepository_Expecter) Update(_a0 interface{}, _a1 interface{}) *MockEmailChallengeRepository_Update_Call {
	return &MockEmailChallengeRepository_Update_Call{Call: _e.mock.On("Update", _a0, _a1)}
}

func (_c *MockEmailChallengeRepository_Update_Call) Run(run func(_a0 context.Context, _a1 domain.Account)) *MockEmailChallengeRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Account))
	})
	return _c
}

func (_c *MockEmailChallengeRepository_Update_Call) Return(_a0 domain.Account, _a1 error) *MockEmailChallengeRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmailChallengeRepository_Update_Call) RunAndReturn(run func(context.Context, domain.Account) (domain.Account, error)) *MockEmailChallengeRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmailChallengeRepository creates a new instance of MockEmailChallengeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailChallengeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailChallengeRepository {
	mock := &MockEmailChallengeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
